[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  
[functions."___netlify-server-handler"]
  memory = 1024
  timeout = 60

[[plugins]]
  package = "@netlify/plugin-nextjs"
